---
artifacts:
  files:
    - hello
phases:
  build:
    commands:
      - "echo Build started on `date`"
      - "echo Compiling the Go code..."
      - "npm install"
  post_build:
    commands:
      - "echo Build completed on `date`"
version: 0.2
