---
containers:
  LambdaFunctions:
    artifacts:
      files:
        - post-saml.yaml
    phases:
      pre_build:
        commands:
          - "echo \"export default {\\n  cognito: {\\n    USER_POOL_ID: \x22$USER_POOL_ID\x22,\\n    APP_CLIENT_ID: \x22$APP_CLIENT_ID\x22\\n  }\\n};\" > src/config.js"
          - "cat src/config.js"
      install:
        commands:
          - "npm install"
      build:
        commands:
          - "npm run build"
      post_build:
        commands:
          - "aws s3 cp --recursive --acl public-read ./src/build s3://$S3_SITE_BUCKET/"
          - "aws cloudformation package --template $INPUT_FILE --s3-bucket $S3_ARTIFACT_BUCKET --output-template post-saml.yaml"

environment_variables:
  plaintext:
    INPUT_FILE: aws/cloudformation/saml.yaml
version: 0.0
