---
containers:
  LambdaFunctions:
    artifacts:
      files:
        - post-saml.yaml
        - beta.json
    phases:
      build:
        commands:
          - "npm run build"
      install:
        commands:
          - "npm install"
      post_build:
        commands:
          - "aws s3 cp --recursive --acl public-read ./src/build s3://$S3_SITE_BUCKET/"
          - "aws cloudformation package --template $INPUT_FILE --s3-bucket $S3_ARTIFACT_BUCKET --output-template post-saml.yaml"
      pre_build:
        commands:
          - "echo -en export default {\\n  cognito: {\\n    USER_POOL_ID: \"$USER_POOL_ID\",\\n    APP_CLIENT_ID: $APP_CLIENT_ID\\n  }\\n}; > config.js"
environment_variables:
  plaintext:
    INPUT_FILE: aws/cloudformation/saml.yaml
version: 0.0
