version: 0.0
environment_variables:
    plaintext:
        "INPUT_FILE": "aws/cloudformation/saml.yaml"
phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - printenv
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 cp --recursive --acl public-read ./src/build s3://$S3_SITE_BUCKET/
      - aws cloudformation package --template $INPUT_FILE --s3-bucket $S3_ARTIFACT_BUCKET --output-template post-saml.yaml
artifacts:
  files:
    - post-saml.yaml
